# Generated by Django 6.1 on 2026-08-24 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_text', models.TextField(help_text="What the learner said they're trying to achieve.")),
                ('target_role', models.CharField(blank=True, max_length=200)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearnerInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='profiles.learnerprofile')),
            ],
            options={
                'unique_together': {('profile', 'label')},
            },
        ),
        migrations.CreateModel(
            name='LearnerSkillEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(help_text='Course/topic name this evidence is about.', max_length=200)),
                ('evidence_level', models.CharField(choices=[('known', 'Known — learner explicitly stated this'), ('inferred', 'Inferred — extracted from free text, not explicitly confirmed'), ('unknown', 'Unknown — no evidence either way')], default='unknown', max_length=20)),
                ('source', models.CharField(default='onboarding_text', help_text='Where this evidence came from, e.g. onboarding_text, learning_history.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profiles.learnerprofile')),
            ],
            options={
                'unique_together': {('profile', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='LearningHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In progress'), ('skipped', 'Skipped'), ('saved', 'Saved')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='profiles.learnerprofile')),
            ],
            options={
                'verbose_name_plural': 'learning history entries',
                'unique_together': {('profile', 'course')},
            },
        ),
    ]
