# Generated by Django 6.1 on 2026-08-24 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
                ('score', models.FloatField()),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='profiles.learnerprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('profile', 'course')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(choices=[('helpful', 'Helpful'), ('not_helpful', 'Not helpful')], max_length=20)),
                ('reason', models.CharField(blank=True, choices=[('too_easy', 'Too easy'), ('too_difficult', 'Too difficult'), ('already_know', 'Already know this'), ('not_relevant', 'Not relevant'), ('wrong_direction', 'Wrong direction'), ('prefer_project', 'Prefer project'), ('prefer_course', 'Prefer course'), ('prefer_resource', 'Prefer article/resource'), ('other', 'Other')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedback', to='profiles.learnerprofile')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='recommender.recommendation')),
            ],
        ),
    ]
