# Generated by Django 6.1 on 2026-08-24 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('goal_snapshot', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.CharField(blank=True, max_length=300)),
                ('is_current', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='profiles.learnerprofile')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('profile', 'version')},
            },
        ),
        migrations.CreateModel(
            name='LearningPathItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
                ('stage', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('current', 'Current'), ('upcoming', 'Upcoming'), ('blocked', 'Blocked')], max_length=20)),
                ('match_score', models.FloatField()),
                ('reason', models.TextField(blank=True)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pathway.learningpath')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='PathChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_version', models.PositiveIntegerField(blank=True, null=True)),
                ('new_version', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_changes', to='profiles.learnerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
