# Generated by Django 6.1 on 2026-08-26 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('profiles', '0002_learnerprofile_internship_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerSavedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_resources', to='profiles.learnerprofile')),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('profile', 'course')},
            },
        ),
    ]
