# Generated by Django 6.1 on 2026-08-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='internship_mode',
            field=models.BooleanField(default=False, help_text='When on, path generation gives a slight tiebreak boost to courses tied to a curated portfolio project.'),
        ),
    ]
